version: '3.8'

services:
  postgres:
    image: pgvector/pgvector:pg17 # Используем самый свежий и официальный образ
    container_name: pvt_postgres_db
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: pvt_admin
      POSTGRES_PASSWORD: pvt_secure_password_2026
      POSTGRES_DB: pvt_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: # ч чтобы данные БД не удалялись при перезапуске контейнера